#!/bin/bash
cat <<EOF
<html>
<head>
<style type=text/css>
table.minimalistBlack {
  border: 3px solid #000000;
  text-align: left;
  border-collapse: collapse;
}
table.minimalistBlack td, table.minimalistBlack th {
  border: 1px solid #000000;
  padding: 5px 4px;
}
table.minimalistBlack tbody td {
  font-size: 13px;
}
table.minimalistBlack thead {
  background: #CFCFCF;
  background: -moz-linear-gradient(top, #dbdbdb 0%, #d3d3d3 66%, #CFCFCF 100%);
  background: -webkit-linear-gradient(top, #dbdbdb 0%, #d3d3d3 66%, #CFCFCF 100%);
  background: linear-gradient(to bottom, #dbdbdb 0%, #d3d3d3 66%, #CFCFCF 100%);
  border-bottom: 3px solid #000000;
}
table.minimalistBlack thead th {
  font-size: 15px;
  font-weight: bold;
  color: #000000;
  text-align: left;
}
table.minimalistBlack tfoot td {
  font-size: 14px;
}
</style>
</head>
<body style="font-family: sans-serif;">
<h1>Aktuel mapping af QR-koder</h1>
EOF

echo "<div style=\"font-size: 10px\">Opdateret "
TZ="Europe/Copenhagen" date
echo "</div><p>"
echo "<table class="minimalistBlack">"
grep HQR /usr/local/lib/qr-redirect/redirect-map.conf | awk '{ gsub("/", "", $1); gsub(";", "", $2); url=$2; gsub("https://wiki.hal9k.dk/", "", $2); printf "<tr><td>%s</td><td><a href=\"%s\">%s</a></td></tr>\n", $1, url, $2 }'
echo "</table>"
echo "</body><html/>"
